# Generated by Django 6.0.2 on 2026-03-20 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points_earned_this_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='week_start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
