# Generated by Django 6.0.2 on 2026-03-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_points_earned_this_week_user_week_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='points_earned_this_week',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_points',
            field=models.FloatField(default=0.0),
        ),
    ]
