# Generated by Django 6.0.2 on 2026-03-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_points_earned_this_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_exclusive_access',
            field=models.BooleanField(default=False),
        ),
    ]
