# Generated by Django 6.0.2 on 2026-03-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_has_exclusive_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test_field',
            field=models.BooleanField(default=False),
        ),
    ]
