export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_FETCH_REQUEST = 'USER_FETCH_REQUEST';
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
export const USER_FETCH_FAIL = 'USER_FETCH_FAIL';

export const USER_PREFERENCES_UPDATE_REQUEST = 'USER_PREFERENCES_UPDATE_REQUEST';
export const USER_PREFERENCES_UPDATE_SUCCESS = 'USER_PREFERENCES_UPDATE_SUCCESS';
export const USER_PREFERENCES_UPDATE_FAIL = 'USER_PREFERENCES_UPDATE_FAIL';
