
export const SCHEDULE_UPLOAD_REQUEST = 'SCHEDULE_UPLOAD_REQUEST';
export const SCHEDULE_UPLOAD_SUCCESS = 'SCHEDULE_UPLOAD_SUCCESS';
export const SCHEDULE_UPLOAD_FAIL = 'SCHEDULE_UPLOAD_FAIL';
export const SCHEDULE_UPLOAD_RESET = 'SCHEDULE_UPLOAD_RESET';

export const SCHEDULE_LIST_REQUEST = 'SCHEDULE_LIST_REQUEST';
export const SCHEDULE_LIST_SUCCESS = 'SCHEDULE_LIST_SUCCESS';
export const SCHEDULE_LIST_FAIL = 'SCHEDULE_LIST_FAIL';