export const TASK_LIST_REQUEST = 'TASK_LIST_REQUEST';
export const TASK_LIST_SUCCESS = 'TASK_LIST_SUCCESS';
export const TASK_LIST_FAIL = 'TASK_LIST_FAIL';

export const TASK_CREATE_REQUEST = 'TASK_CREATE_REQUEST';
export const TASK_CREATE_SUCCESS = 'TASK_CREATE_SUCCESS';
export const TASK_CREATE_FAIL = 'TASK_CREATE_FAIL';

export const TASK_COMPLETE_REQUEST = 'TASK_COMPLETE_REQUEST';
export const TASK_COMPLETE_SUCCESS = 'TASK_COMPLETE_SUCCESS';
export const TASK_COMPLETE_FAIL = 'TASK_COMPLETE_FAIL';

export const TASK_SCAN_REQUEST = 'TASK_SCAN_REQUEST'
export const TASK_SCAN_SUCCESS = 'TASK_SCAN_SUCCESS'
export const TASK_SCAN_FAIL = 'TASK_SCAN_FAIL'

export const TASK_BULK_CREATE_REQUEST = 'TASK_BULK_CREATE_REQUEST'
export const TASK_BULK_CREATE_SUCCESS = 'TASK_BULK_CREATE_SUCCESS'
export const TASK_BULK_CREATE_FAIL = 'TASK_BULK_CREATE_FAIL'

export const TASK_SCAN_RESET = 'TASK_SCAN_RESET'