# Generated by Django 6.0.2 on 2026-02-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='duration_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='points_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
