# Generated by Django 6.0.2 on 2026-03-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_deadline_task_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='prioritized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='task',
            name='priority_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='priority_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='task',
            name='priority_source',
            field=models.CharField(blank=True, default='rules', max_length=64),
        ),
    ]
