# Generated by Django 6.0.2 on 2026-03-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='points_value',
            field=models.FloatField(default=0.0),
        ),
    ]
